#
# ~/.tmux.conf
#

# prefix
unbind C-b
set -g prefix C-a
bind a send-prefix

# basic options
setw -g automatic-rename
set -g  base-index 1
set -g default-shell "$SHELL"
set -g default-command "$SHELL"
set -g  default-terminal "screen-256color"
set -g  display-time 4000
set -sg escape-time 0
set -g focus-events on
set -g  history-limit 50000
set -wg mode-keys vi
set -g  mouse on
set -wg pane-base-index 1
set -g  status-interval 5
set -g  renumber-windows on

# reload tmux config
bind r source-file ~/.tmux.conf

# switch window
bind c new-window -c "#{pane_current_path}"
bind C-a last-window

# split window
unbind '"'
bind '\' split-window -h -c "#{pane_current_path}"
bind | split-window -hf -c "#{pane_current_path}"
unbind %
bind - split-window -v -c "#{pane_current_path}"
bind _ split-window -vf -c "#{pane_current_path}"

# switch pane with hjkl
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# switch pane with alt+arrows
bind-key -n M-Up select-pane -U
bind-key -n M-Left select-pane -L
bind-key -n M-Down select-pane -D
bind-key -n M-Right select-pane -R

# status bar
set -g status-style fg=colour244
set -g window-status-current-style fg=colour222
set -g pane-border-style fg=colour240
set -g pane-active-border-style fg=colour243
set -g status-left ''
set -g status-left-length 0
set -g status-right ''
set -g status-right-length 0
set -g status-right '%a %Y-%m-%d %H:%M'
set -g status-right-length 20
