#!/bin/sh

# parse arguments and set defaults
REPODIR="$HOME/.config/dotfiles"
DOTBACKUP="${REPODIR}-backup"
REMOTE='https://github.com/bepoli/dotfiles'
while getopts 'd:r:' opt; do
    case "$opt" in
        'd')
            REPODIR="$OPTARG"
            ;;
        'r')
            REMOTE="$OPTARG"
            ;;
    esac
done

# initialize dotfiles
cd "$HOME"
git clone --bare "$REMOTE" "$REPODIR"
alias config='git --git-dir="$REPODIR" --work-tree="$HOME"'
for f in $(config ls-tree --full-tree -r HEAD | cut -f2); do
    d="$(dirname $f)"
    if [ -f "$HOME/$f" ]; then
        mkdir -p "$DOTBACKUP/$d"
        mv -f "$HOME/$f" "$DOTBACKUP/$f"
    fi
done
config checkout
config sparse-checkout set --no-cone '/**' '!bootstrap' '!README.md' '!LICENSE'
config config --local status.showUntrackedFiles no
unset REPODIR DOTBACKUP REMOTE d f
